apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-extras
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/dgpark3675/Soldout.git
    targetRevision: main
    path: manifests/apps
    directory:
      recurse: false                            # 하위 폴더 까지 안 보게 
      include: "app-kube-prometheus-stack.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
