apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prometheus-stack
  namespace: argo-cd   
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "77.5.0"
    helm:
      
      skipCrds: true
      values: |
        fullnameOverride: kps

        # kube-prometheus-stack가 제공하는 CRDs 설치
        crds:
          enabled: false

        # Alertmanager를 당분간 완전히 끔(중복/충돌 방지)
        alertmanager:
          enabled: false

        grafana:
          adminUser: admin
          adminPassword: "1q2w3e4r!"
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
          persistence:
            enabled: false
          defaultDashboardsTimezone: Asia/Seoul
          ingress:
            enabled: false
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: prod-eks
            scrapeInterval: 30s
            evaluationInterval: 30s
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            nodeSelector:
              eks.amazonaws.com/nodegroup: Monitoring
            tolerations:
              - key: role
                operator: Equal
                value: monitoring
                effect: NoSchedule

        # ← 여기 'prometheus-node-exporter'의 값 경로가 중요합니다.
        prometheus-node-exporter:
          tolerations:
            - key: role
              operator: Equal
              value: was
              effect: NoSchedule
            - key: role
              operator: Equal
              value: web
              effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: eks.amazonaws.com/nodegroup
                        operator: In
                        values:
                          - Private-was
                          - Public-web

        prometheusOperator:
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

        kube-state-metrics:
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations
