apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-extras
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dgpark3675/Soldout.git
    targetRevision: main
    path: manifests/monitoring/extras
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true