apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prometheus-stack
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "77.6.2"
    helm:
      # ⬇️ 자동 CRD 설치 켠다
      skipCrds: true
      values: |
        fullnameOverride: kps

        # ⬇️ 차트가 제공하는 CRDs 설치(자동)
        crds:
          enabled: false

        # Alertmanager는 일단 비활성(원하면 나중에 다시 켬)
        alertmanager:
          enabled: false

        grafana:
          adminUser: admin
          adminPassword: "1q2w3e4r!"
          service:
            type: LoadBalancer
            # annotations:
            #   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            #   service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
          persistence:
            enabled: false
          defaultDashboardsTimezone: Asia/Seoul
          ingress:
            enabled: false
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

        prometheus:
          enabled: true
          prometheusSpec:
            version: v3.5.0
            replicas: 2 
            externalLabels:
              cluster: prod-eks
            scrapeInterval: 30s
            evaluationInterval: 30s
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            storageSpec: {} 
            affinity: {}
            topologySpreadConstraints:
             # ① 노드 단위 분산
              - maxSkew: 2
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: ScheduleAnyway
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: prometheus
                    app.kubernetes.io/instance: kps-prometheus
                     # ② 가용영역(AZ) 단위 분산
              - maxSkew: 2
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: ScheduleAnyway
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: prometheus
                    app.kubernetes.io/instance: kps-prometheus
            nodeSelector:
              eks.amazonaws.com/nodegroup: Monitoring
            tolerations:
              - key: role
                operator: Equal
                value: monitoring
                effect: NoSchedule

        # web/was 노드에만 node-exporter
        prometheus-node-exporter:
          tolerations:
            - key: role
              operator: Equal
              value: was
              effect: NoSchedule
            - key: role
              operator: Equal
              value: web
              effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: eks.amazonaws.com/nodegroup
                        operator: In
                        values:
                          - Private-was
                          - Public-web

        prometheusOperator:
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

        kube-state-metrics:
          nodeSelector:
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true   # ⬅️ last-applied 주석 없이 서버사이드 적용(용량 문제 예방)
      - RespectIgnoreDifferences=true
      - Validate=false
      - SkipDryRunOnMissingResource=true

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - .metadata.annotations    # ⬅️ CRD의 annotations 차이는 무시(Argo가 패치 안 하게)
