apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prometheus-stack
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: ""  
    helm:
      values: |
        fullnameOverride: kps-grafana

        grafana:
          adminUser: admin
          adminPassword: "1q2w3e4r!"       
          service:
            type: ClusterIP
          persistence:
            enabled: false
          defaultDashboardsTimezone: Asia/Seoul
          ingress:
            enabled: false                   # 인그레스는 별도 파일로 관리
          nodeSelector:                        # --set grafana.nodeSelector.role=monitoring
            eks.amazonaws.com/nodegroup: Monitoring
          tolerations:                         # --set grafana.tolerations[0].*
            - key: role
              operator: Equal
              value: monitoring
              effect: NoSchedule



        prometheus:
          prometheusSpec:
            externalLabels:
              cluster: prod-eks              # 사람이 보기 좋은 태그(실제 EKS 이름과 달라도 됨)
            scrapeInterval: 30s
            evaluationInterval: 30s
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            podMonitorSelector: {}
            nodeSelector:                      # --set prometheus.prometheusSpec.nodeSelector.role=monitoring
              eks.amazonaws.com/nodegroup: Monitoring
            tolerations:                       # --set prometheus.prometheusSpec.tolerations[0].*
              - key: role
                operator: Equal
                value: monitoring
                effect: NoSchedule
         
        alertmanager:
          alertmanagerSpec:
            nodeSelector:                      # --set alertmanager.nodeSelector.role=monitoring
              eks.amazonaws.com/nodegroup: Monitoring
            tolerations:                       # --set alertmanager.tolerations[0].*
              - key: role
                operator: Equal
                value: monitoring
                effect: NoSchedule
          config:
            global:
              resolve_timeout: 5m
              time_zone: Asia/Seoul
            route:
              receiver: "null"
            receivers:
              - name: "null"
        
        
        # 기본 컴포넌트 활성
        kube-state-metrics:
          rbac:
            create: true

        nodeExporter:
          enabled: true

  destination:
    server: https://kubernetes.default.svc   # 같은(기존) 클러스터에 배포
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

