apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - name: web
        image: namme/web:latest
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: web-nginx

---
apiVersion: v1
kind: Service
metadata:
  name: web-nginx-svc
spec:
  type: LoadBalancer
  selector:
    app: web-nginx
  ports:
  - port: 80
    targetPort: 80
    #nodePort: 30080